### ISSUE TITLE
Screen Turning to White

### ISSUE THREAD

**Issue by snietop** [tangrams/heightmapper#30]
Using google chrome to access the site. When zooming in the map will go completely white. I have tried adjusting the exposure to no avail. It is almost as though it is unable to load areas that have not already been loaded.

**Comment by Hokkins** [comment]
> Использование Google Chrome для доступа к сайту. При приближении карта станет полностью белой. Я безуспешно пытался отрегулировать экспозицию. Это похоже на то, как будто он не может загрузить области, которые еще не были загружены.

Absolutely the same problem!

**Comment by DmitriyZ21** [comment]
Yes. Also the same problem. It says it is because of CORS. 
![crashes](https://user-images.githubusercontent.com/86230710/122770723-670d4f00-d2ae-11eb-980e-7cfdc262573c.jpg)
I tried to turn off security in Chrome but it did not help. Also I launched localhost, here are issues:
![crashes_localhost](https://user-images.githubusercontent.com/86230710/122771002-afc50800-d2ae-11eb-98d6-5ddf2423a413.jpg)
Nothing helped me, now I'll try to change API key.

**Comment by Hokkins** [comment]
> Да. Тоже такая же проблема. Он говорит, что это из-за CORS. Я попытался отключить безопасность в Chrome, но это не помогло. Также я запустил localhost, вот проблемы: Ничего не помогло, сейчас попробую сменить ключ API.
> ![сбои](https://user-images.githubusercontent.com/86230710/122770723-670d4f00-d2ae-11eb-980e-7cfdc262573c.jpg)
> 
> ![crashes_localhost](https://user-images.githubusercontent.com/86230710/122771002-afc50800-d2ae-11eb-98d6-5ddf2423a413.jpg)

As far as I understand, the official support of this site has long been completed, is there a chance that you will be able to restore the site's functionality?

**Comment by derakon** [comment]
This is happening to me now as well:

Access to image at 'https://tile.nextzen.org/tilezen/terrain/v1/256/terrarium/2/3/3.png?api_key=dmlO1fVQRPKI-GrVIYJ1YA&' from origin 'https://tangrams.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

If there's anything I can do to help fix this, please let me know! I have been relying on this tool, and have no backups available.

**Comment by meetar** [comment]
This is a periodic problem but ultimately out of our control. :/ The underlying issue is that since Mapzen closed, the tile service has been funded by donations at minimal service levels with no guarantees of uptime, and requires occasional volunteer maintenance labor on the part of the Nextzen tiles team. It nearly always clears up within a day or two, and if it doesn’t I’ll check in with them about it. Sorry about the downtime, and thanks for your patience!
