### ISSUE TITLE
[Suggestion] Increase the render multiplier up to 16 or 32

### ISSUE THREAD

**Issue by DuranGH2** [tangrams/heightmapper#36]

**Comment by meetar** [comment]
Hi @DuranGH2, thanks for the issue – this would definitely be a very cool feature. However, the render multiplier increases the number of requested tiles exponentially, by powers of 2 – so for a 8x render multiplier, up to 64x the number of tiles may be requested. If the limit were 16, that could be a 256x increase, and 32x would be 1024x increase!

Given the free and public nature of this app, 8x is the maximum I'm comfortable enabling by default. However, this repo is open source, so you are welcome to clone it, make the change, and run it locally. In order to do that you'll need to get your own API key at https://developers.nextzen.org/, which will come with its own request limits – then use that key in place of the key in the `scene.yaml` file. This will allow you to set the values however you wish without potentially disabling the service for others. This technique is what I use when I need a super-large heightmap, although I don't think I've tried anything past 16 – let me know how it goes!
